<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <RootNamespace>LockGate.App</RootNamespace>
    <AssemblyName>LockGate.App</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LockGate.Core\LockGate.Core.csproj" />
    <ProjectReference Include="..\LockGate.Infrastructure\LockGate.Infrastructure.csproj" />
  </ItemGroup>
</Project>
