<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>LockGate.Core.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LockGate.Core\LockGate.Core.csproj" />
    <ProjectReference Include="..\..\src\LockGate.Infrastructure\LockGate.Infrastructure.csproj" />
  </ItemGroup>
</Project>
